 - name: Update yum cache
   yum:
        update_cache: yes

 - name: Install Nginx
   yum:
        name: nginx
        state: latest
 - name: Ensure Nginx service is running and enabled
   service:
        name: nginx
        state: started
        enabled: yes  
 - name: Disable default Nginx site
   file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
         
 - name: Copy Nginx site configuration
   template:
            src: templates/nginx.conf.j2
            dest: /etc/nginx/conf.d/nginx.conf
            owner: nginx
            group: nginx
            mode: '0644'
   notify: restart nginx
   

   
 