- name: Update yum cache
  ansible.builtin.dnf:
    update_cache: true
- name: Install common packages
  ansible.builtin.dnf:
    name:
      - git
      - vim
      - wget
    state: present 
- name: Install fail2ban
  ansible.builtin.dnf:
    name: fail2ban
    state: present    